{% set name = "ax-platform" %}
{% set version = "0.2.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ax-platform-{{ version }}.tar.gz
  sha256: 9962c7e2a0b232e37b92f82f5ff215ea55a2baf00a89601153d0ed317eee39ab

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools >=34.4
    - setuptools-scm
  run:
    - botorch >=0.6.6
    - jinja2
    - pandas
    - plotly
    - python >=3.7
    - scikit-learn
    - scipy
    - typeguard

test:
  imports:
    - ax
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/facebook/Ax
  summary: Adaptive Experimentation
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rpanai
    - thewchan
