{% set name = "ax-platform" %}
{% set version = "0.2.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ax-platform-{{ version }}.tar.gz
  sha256: 7a184f2db38d6b7406c8d8cf668613b7107146c0e9a2476f5d3110ca044a28b0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - botorch ==0.6.2
    - jinja2
    - multipledispatch
    - sqlalchemy
    - pandas
    - plotly
    - python >=3.7
    - scikit-learn
    - scipy
    - typeguard

test:
  imports:
    - ax
    - ax.benchmark
    - ax.benchmark.botorch_modular
    - ax.benchmark.tests
    - ax.core
    - ax.core.tests
    - ax.early_stopping
    - ax.early_stopping.strategies
    - ax.early_stopping.tests
    - ax.exceptions
    - ax.metrics
    - ax.metrics.tests
    - ax.modelbridge
    - ax.modelbridge.strategies
    - ax.modelbridge.tests
    - ax.modelbridge.transforms
    - ax.models
    - ax.models.discrete
    - ax.models.numpy
    - ax.models.random
    - ax.models.tests
    - ax.models.torch
    - ax.models.torch.botorch_modular
    - ax.models.torch.tests
    - ax.plot
    - ax.plot.css
    - ax.plot.js
    - ax.plot.js.common
    - ax.plot.tests
    - ax.runners
    - ax.service
    - ax.service.tests
    - ax.service.utils
    - ax.storage
    - ax.storage.json_store
    - ax.storage.json_store.tests
    - ax.storage.sqa_store
    - ax.storage.sqa_store.tests
    - ax.utils
    - ax.utils.common
    - ax.utils.common.tests
    - ax.utils.flake8_plugins
    - ax.utils.measurement
    - ax.utils.measurement.tests
    - ax.utils.notebook
    - ax.utils.report
    - ax.utils.report.resources
    - ax.utils.report.tests
    - ax.utils.stats
    - ax.utils.stats.tests
    - ax.utils.testing
    - ax.utils.testing.metrics
    - ax.utils.testing.tests
    - ax.utils.tutorials
  commands:
    - pip check
    - pytest -vvv --capture-sys .
  requires:
    - pip
    - pytest

about:
  home: https://github.com/facebook/Ax
  summary: Adaptive Experimentation
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rpanai
    - thewchan
